spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bosko_prod?useSSL=false&serverTimezone=UTC
    username: bosko_prod_user
    password: pass
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true